### ISSUE TITLE
Interface for add_rewrite_rule

### ISSUE THREAD

**Issue by doc987** [wp-cli/rewrite-command#27]
Is there a a way to [add a rewrite rule](https://codex.wordpress.org/Rewrite_API/add_rewrite_rule) with wp-cli?

**Comment by swissspidy** [comment]
Rewrite rules need to be added in a plugin or theme and then rewrite rules need to be updated in the database afterwards.

Although the rewrite rules are stored in the database, they should still be in the plugin so that you can remove them upon deactivation.

So as you can see, this isn‘t really something WP-CLI could do.

**Comment by schlessera** [comment]
Yes, indeed. WP-CLI can only make changes that can be persisted into the database. For changes that need to be persisted in code, there's no default location for WP-CLI to act on.
