### ISSUE TITLE
Improve 'wp rewrite' command description

### ISSUE THREAD

**Issue by hearvox** [wp-cli/rewrite-command#8]
Improve command description in:
https://github.com/wp-cli/rewrite-command/blob/master/src/Rewrite_Command.php
Command: wp rewrite
Current description: Manage rewrite rules.

Proposed description:
Lists or flushes the site's rewrite rules, updates the permalink structure.

See the WordPress [Rewrite API](https://codex.wordpress.org/Rewrite_API) and [WP Rewrite](https://codex.wordpress.org/Class_Reference/WP_Rewrite) class reference.

**Comment by miya0001** [comment]
Related:
https://github.com/wp-cli/wp-cli/issues/4302

**Comment by trainoasis** [comment]
It doesn't seem right to open the new ticket for this question so I'm posting it here since it relates to command descriptions. Feel free to point me in the right direction if this should be asked elsewhere. 

What's the difference between 
- what happens when you visit Settings -> Permalinks

and

- wp rewrite flush?

Was wondering what exactly happens with both since wp rewrite flush doesn't seem to help when I want to fix my permalinks after script deploy.
